// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    help: "Analyzes Oracle R12 updgrade files in specified folder.\nUsage: $0",
    noDestinationFolder: "Specify destination folder.",
    noFiles: "Oracle R12 upgrade files were not found in specified folder.",
    pathDoesNotExist: "Specified path does not exist!",
    tooManyParameters: "Too many parameters. Specify path to destination folder.",
    parsingComplete: "Detected $0 changes for $1 in $2s. File size: $3MB",
    logicChange: 'Logic Change',
    attributeChange: 'Attribute Change',
    objectRemoved: 'Removed',
    attributesChangeMessage: "Types or number of arguments has changed",
    ledgerComment: "col LEDGER_ID added, set_of_books_id has never existed in the table"
  };

}).call(this);
