// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    help: "Analyzes Oracle R12 updgrade files in specified folder.\nUsage: $0",
    noDestinationFolder: "Specify destination folder.",
    noFiles: "Oracle R12 upgrade files were not found in specified folder.",
    pathDoesNotExist: "Specified path does not exist!",
    tooManyParameters: "Too many parameters. Specify path to destination folder.",
    parsingComplete: "Detected $0 changes for $1 in $2s",
    attributeChange: 'Attribute Changed',
    objectRemoved: 'Removed',
    attributesChangeMessage: "Types or number of arguments has changed"
  };

}).call(this);
