// Generated by CoffeeScript 1.4.0
(function() {
  var _;

  _ = require('underscore');

  module.exports = {
    synonym: function(text, lookup) {
      var result;
      result = text;
      _.each(lookup, function(elem) {
        if (text.match(RegExp(elem.pattern, 'gim'))) {
          return result = elem.synonym || text;
        }
      });
      return result;
    },
    testPatterns: function(text, patterns) {
      var result;
      result = false;
      _.each(_.toArray(patterns), function(elem) {
        return result || (result = text.match(RegExp(elem, 'gim')));
      });
      return result;
    },
    testRegex: function(fn, tmpl) {
      var result, source;
      result = {
        detected: false
      };
      if (!_.isObject(tmpl)) {
        return result;
      }
      source = _.isFunction(tmpl.data) ? tmpl.data(fn) : fn;
      if (!_.isArray(source)) {
        source = [source];
      }
      if (!tmpl.pattern) {
        result.detected = source && source.length > 0;
        result.result = source;
      } else {
        _.each(source, function(elem) {
          var parsedData;
          if (elem.match(RegExp(tmpl.pattern, tmpl.options || "gim"))) {
            result.detected = true;
            if (_.isFunction(tmpl.parse)) {
              parsedData = tmpl.parse(elem);
              if (parsedData) {
                return _.extend(result, parsedData);
              } else {
                return result.detected = false;
              }
            }
          }
        });
      }
      return result;
    }
  };

}).call(this);
